services:
  db:
    image: postgres:16-alpine
    container_name: issue_tracker_db
    environment:
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: tracker_password
      POSTGRES_DB: issue_tracker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - issue_tracker_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tracker_user -d issue_tracker']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  issue_tracker_network:
    driver: bridge
