services:
  db:
    image: mysql:8.0
    container_name: issue_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: issue_tracker
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: tracker_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - issue_tracker_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppassword']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  issue_tracker_network:
    driver: bridge
